# Generated by Django 4.2.24 on 2025-12-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barrios', '0001_initial'),
        ('servicios', '0001_initial'),
        ('abonados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pegue', models.CharField(max_length=6, unique=True)),
                ('estado', models.CharField(choices=[('HAB', 'Habilitada'), ('INH', 'Inhabilitada'), ('CRT', 'Cortada')], default='HAB', max_length=10)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegues', to='abonados.abonado')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonados', to='barrios.barrio')),
                ('linea_distribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonados', to='servicios.lineadistribucion')),
                ('servicios', models.ManyToManyField(related_name='abonados', to='servicios.servicio')),
            ],
        ),
    ]
