# Generated by Django 6.0.2 on 2026-02-17 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonados', '0001_initial'),
        ('barrios', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pegue', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_uppercase', message='Solo se permiten letras mayúsculas y números.', regex='^[A-Z0-9]*$')])),
                ('estado', models.CharField(choices=[('HAB', 'Habilitada'), ('INH', 'Inhabilitada'), ('CRT', 'Cortada')], default='HAB', max_length=10)),
                ('tipo', models.CharField(choices=[('VIV', 'Vivienda'), ('COR', 'Corral'), ('SOL', 'Solar'), ('COM', 'Comercio')], default='VIV', max_length=10)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pegues', to='abonados.abonado')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonados', to='barrios.barrio')),
                ('linea_distribucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonados', to='servicios.lineadistribucion')),
                ('servicios', models.ManyToManyField(related_name='abonados', to='servicios.servicio')),
            ],
        ),
    ]
