# Generated by Django 4.2.24 on 2025-12-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegue',
            name='tipo',
            field=models.CharField(choices=[('VIV', 'Vivienda'), ('COR', 'Corral'), ('SOL', 'Solar'), ('COM', 'Comercio')], default='VIV', max_length=10),
        ),
    ]
