# Generated by Django 6.0.2 on 2026-02-12 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegues', '0002_pegue_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegue',
            name='codigo_pegue',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_uppercase', message='Solo se permiten letras mayúsculas y números.', regex='^[A-Z0-9]*$')]),
        ),
    ]
