# Generated by Django 4.2.24 on 2025-12-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, default='', max_length=13, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
