# Generated by Django 6.0.1 on 2026-01-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonado',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=13, null=True, unique=True),
        ),
    ]
